In [ ]:
!pip install datasets


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 510.5/510.5 kB 11.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 17.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 26.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 20.4 MB/s eta 0:00:00


In [ ]:
import tensorflow as tf
from transformers import TFAutoModel, AutoTokenizer
from datasets import load_dataset

In [ ]:
model = TFAutoModel.from_pretrained('bert-base-multilingual-cased')

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/625 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/714M [00:00<?, ?B/s]

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.weight', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

In [ ]:
from transformers import BertTokenizer
# Load the multilingual BERT tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-cased')

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/996k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

In [ ]:
inputs = tokenizer(['Hello world', 'Hi how are you'], padding=True, truncation=True,
                  return_tensors='tf')
inputs

{'input_ids': <tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[  101, 31178, 11356,   102,     0,     0],
       [  101, 20065, 14796, 10301, 13028,   102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [ ]:
output = model(inputs)
output

TFBaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=<tf.Tensor: shape=(2, 6, 768), dtype=float32, numpy=
array([[[-1.28848135e-01, -8.29536676e-01,  1.08536005e+00, ...,
          5.10796979e-02, -2.50096560e-01, -3.54952842e-01],
        [-2.75410295e-01, -1.26741242e+00,  9.98244286e-01, ...,
          7.08755702e-02, -2.07902044e-01, -5.94258428e-01],
        [-2.89131463e-01, -1.45810628e+00,  1.17758632e+00, ...,
         -2.50020802e-01, -1.22902766e-01, -6.09884381e-01],
        [-5.04239574e-02, -1.12271857e+00,  1.45674181e+00, ...,
         -1.91058695e-01, -2.60177076e-01, -2.80655265e-01],
        [-5.48609942e-02, -9.83054936e-01,  1.10246325e+00, ...,
          1.66599564e-02, -2.27825642e-01, -2.97335029e-01],
        [-2.06225514e-02, -1.01458466e+00,  1.14159226e+00, ...,
          4.06107828e-02, -1.87947169e-01, -2.49661416e-01]],

       [[-5.10689951e-02, -6.24208897e-02,  6.69195414e-01, ...,
          8.03123415e-01, -5.63445210e-01,  1.05505079e-01]

In [ ]:
import pandas as pd
import tensorflow as tf
from transformers import TFAutoModel, AutoTokenizer
from datasets import Dataset
# Load your dataset from CSV file
file_path = "faan.csv"
your_dataset = pd.read_csv(file_path)

# Convert the DataFrame to a Hugging Face Dataset
your_dataset = Dataset.from_pandas(your_dataset)

FileNotFoundError: [Errno 2] No such file or directory: 'faan.csv'

In [ ]:
emotions = load_dataset('SetFit/emotion')

/usr/local/lib/python3.10/dist-packages/huggingface_hub/repocard.py:105: UserWarning: Repo card metadata block was not found. Setting CardData to empty.
  warnings.warn("Repo card metadata block was not found. Setting CardData to empty.")


In [ ]:
#your_dataset


import zipfile
import os

# Path to the uploaded ZIP file
zip_file_path = '/content/check.zip'

# Directory to extract the contents
extraction_path = '/content/check/'

# Unzip the file
with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extraction_path)

# List the extracted files
extracted_files = os.listdir(extraction_path)
print("Extracted files:", extracted_files)


Extracted files: ['Validation', 'Train', 'Test']


In [ ]:
from datasets import Dataset

# Load the dataset
test = Dataset.load_from_disk("/content/check/Test")
train = Dataset.load_from_disk("/content/check/Train")
Validation = Dataset.load_from_disk("/content/check/Validation")


test
train
Validation

Dataset({
    features: ['text', 'label', 'label_text'],
    num_rows: 143
})

In [ ]:
from datasets import Dataset, DatasetDict
# Create a DatasetDict
emotions = DatasetDict({
    'train': train,
    'validation': Validation,
    'test': test
})
emotions


DatasetDict({
    train: Dataset({
        features: ['text', 'label', 'label_text'],
        num_rows: 1235
    })
    validation: Dataset({
        features: ['text', 'label', 'label_text'],
        num_rows: 143
    })
    test: Dataset({
        features: ['text', 'label', 'label_text'],
        num_rows: 99
    })
})

In [ ]:
emotions

DatasetDict({
    train: Dataset({
        features: ['text', 'label', 'label_text'],
        num_rows: 1235
    })
    validation: Dataset({
        features: ['text', 'label', 'label_text'],
        num_rows: 143
    })
    test: Dataset({
        features: ['text', 'label', 'label_text'],
        num_rows: 99
    })
})

In [ ]:
def tokenize(batch):
    return tokenizer(batch["text"], padding=True, truncation=True)

In [ ]:
emotions_encoded = emotions.map(tokenize, batched=True, batch_size=None)

Map:   0%|          | 0/1235 [00:00<?, ? examples/s]

Map:   0%|          | 0/143 [00:00<?, ? examples/s]

Map:   0%|          | 0/99 [00:00<?, ? examples/s]

In [ ]:
emotions_encoded

DatasetDict({
    train: Dataset({
        features: ['text', 'label', 'label_text', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 1235
    })
    validation: Dataset({
        features: ['text', 'label', 'label_text', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 143
    })
    test: Dataset({
        features: ['text', 'label', 'label_text', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 99
    })
})

In [ ]:
# setting 'input_ids', 'attention_mask', 'token_type_ids', and 'label'
# to the tensorflow format. Now if you access this dataset you will get these
# columns in `tf.Tensor` format

emotions_encoded.set_format('tf',
                            columns=['input_ids', 'attention_mask', 'token_type_ids', 'label'])

# setting BATCH_SIZE to 64.
BATCH_SIZE = 8

def order(inp):
    '''
    This function will group all the inputs of BERT
    into a single dictionary and then output it with
    labels.
    '''
    data = list(inp.values())
    return {
        'input_ids': data[1],
        'attention_mask': data[2],
        'token_type_ids': data[3]
    }, data[0]

# converting train split of `emotions_encoded` to tensorflow format
train_dataset = tf.data.Dataset.from_tensor_slices(emotions_encoded['train'][:])
# set batch_size and shuffle
train_dataset = train_dataset.batch(BATCH_SIZE).shuffle(1000)
# map the `order` function
train_dataset = train_dataset.map(order, num_parallel_calls=tf.data.AUTOTUNE)

# ... doing the same for test set ...
test_dataset = tf.data.Dataset.from_tensor_slices(emotions_encoded['test'][:])
test_dataset = test_dataset.batch(BATCH_SIZE)
test_dataset = test_dataset.map(order, num_parallel_calls=tf.data.AUTOTUNE)

In [ ]:
inp, out = next(iter(train_dataset)) # a batch from train_dataset
print(inp, '\n\n', out)

{'input_ids': <tf.Tensor: shape=(8, 168), dtype=int64, numpy=
array([[   101,    107,    125, ...,      0,      0,      0],
       [   101,    107,    170, ...,      0,      0,      0],
       [   101,    107, 110142, ...,      0,      0,      0],
       ...,
       [   101,    107,  10422, ...,      0,      0,      0],
       [   101,    107,  91327, ...,      0,      0,      0],
       [   101,    107,  12342, ...,      0,      0,      0]])>, 'attention_mask': <tf.Tensor: shape=(8, 168), dtype=int64, numpy=
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])>, 'token_type_ids': <tf.Tensor: shape=(8, 168), dtype=int64, numpy=
array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]])>} 

 tf

In [ ]:
class BERTForClassification(tf.keras.Model):
    def __init__(self, bert_model, num_classes):
        super().__init__()
        self.bert = bert_model
        self.fc = tf.keras.layers.Dense(num_classes, activation='softmax')

    def call(self, inputs, attention_mask=None, token_type_ids=None):
        outputs = self.bert(inputs, attention_mask=attention_mask, token_type_ids=token_type_ids)
        pooled_output = outputs[1]  # Assuming BERT returns pooled output in position 1
        return self.fc(pooled_output)

    def get_config(self):
        config = super().get_config()
        config.update({
            'bert_model': self.bert,
            'num_classes': self.fc.units
        })
        return config


In [ ]:
classifier = BERTForClassification(model, num_classes=5)

classifier.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),
    loss=tf.keras.losses.SparseCategoricalCrossentropy(),
    metrics=['accuracy']
)

In [ ]:
history = classifier.fit(
    train_dataset,
    epochs=10
)

Epoch 1/10
155/155 [==============================] - 113s 304ms/step - loss: 1.2096 - accuracy: 0.5126
Epoch 2/10
155/155 [==============================] - 46s 295ms/step - loss: 0.6990 - accuracy: 0.7368
Epoch 3/10
155/155 [==============================] - 46s 296ms/step - loss: 0.4654 - accuracy: 0.8364
Epoch 4/10
155/155 [==============================] - 46s 296ms/step - loss: 0.2300 - accuracy: 0.9206
Epoch 5/10
155/155 [==============================] - 46s 297ms/step - loss: 0.1053 - accuracy: 0.9668
Epoch 6/10
155/155 [==============================] - 46s 297ms/step - loss: 0.0489 - accuracy: 0.9887
Epoch 7/10
155/155 [==============================] - 46s 300ms/step - loss: 0.0398 - accuracy: 0.9895
Epoch 8/10
155/155 [==============================] - 47s 304ms/step - loss: 0.0237 - accuracy: 0.9935
Epoch 9/10
155/155 [==============================] - 47s 301ms/step - loss: 0.0492 - accuracy: 0.9822
Epoch 10/10
155/155 [==============================] - 47s 303ms/step - 

In [ ]:
classifier.evaluate(test_dataset)

13/13 [==============================] - 10s 73ms/step - loss: nan - accuracy: 0.8990


[nan, 0.8989899158477783]

In [ ]:
# # Assuming your BERTForClassification model is named 'classifier' and has been fine-tuned
# classifier.save_weights('model_weightss.tf')

# Assuming you have a trained BERT model object named 'model' and a tokenizer object named 'tokenizer'

# Save the model weights
classifier.save_weights('bert_model.h5')

# Save the tokenizer
tokenizer.save_pretrained('bert_tokenizer')

('bert_tokenizer/tokenizer_config.json',
 'bert_tokenizer/special_tokens_map.json',
 'bert_tokenizer/vocab.txt',
 'bert_tokenizer/added_tokens.json')

In [ ]:
# List of testing lines
testing_lines = [
    "BERT aik acha model hai?? btao zra",
    "Very nice explanation thanks",
    "Am a commerce background can I learn it?",
    "Hi .kasi hai ap main ap ko bhot follow krti hon main computer science ki student ho but medical background ha mera 1st semester ha or main achy sa coding sekhna chahti hon c language sekh rahi hon lakin abhi tak mughy nahi ati c language kia karon kasa logic build karon",
    "Cloud computing as a fresher good or not ?",
    "Mam please c++ language video",
    "Aap bolti bahut aache se hain",
    "Didi eek video VOIP pae bana lon mera exam hai",
    "Need a roadmap for cloud computing and projects that can be done on them"
]

# Tokenize and preprocess the new data
inputs = tokenizer(testing_lines, padding=True, truncation=True, return_tensors='tf')

# Extract input tensors
input_ids = inputs['input_ids']
attention_mask = inputs['attention_mask']
token_type_ids = inputs['token_type_ids']


print("Input IDs shape:", input_ids)
print("Attention mask shape:", attention_mask)
print("Token type IDs shape:", token_type_ids)


# Predict labels for the new data using the trained model
predictions = classifier.predict({'input_ids': input_ids, 'attention_mask': attention_mask, 'token_type_ids': token_type_ids})

# The `predictions` variable now contains the predicted labels for the new data
print(predictions)


Input IDs shape: tf.Tensor(
[[   101  46291  46935  11346  10174  33478  10113  13192  13080    136
     136    170  50456    194  10288    102      0      0      0      0
       0      0      0      0      0      0      0      0      0      0
       0      0      0      0      0      0      0      0      0      0
       0      0      0      0      0      0      0      0      0      0
       0      0      0      0      0      0      0      0      0      0
       0      0      0      0      0      0      0      0      0      0
       0]
 [   101  37282  46267  10112  88840  69892    102      0      0      0
       0      0      0      0      0      0      0      0      0      0
       0      0      0      0      0      0      0      0      0      0
       0      0      0      0      0      0      0      0      0      0
       0      0      0      0      0      0      0      0      0      0
       0      0      0      0      0      0      0      0      0      0
       0      0      0    

In [ ]:
import numpy as np

# Convert predictions to numpy array
predictions_array = np.array(predictions)

# Get the index of the class with the highest probability for each prediction
dominating_classes_index = np.argmax(predictions_array, axis=1)

# Define the classes corresponding to the indices
classes = ['Positive', 'Negative', 'Neutral', 'Recommendation', 'Question']

# Get the dominating class for each prediction
dominating_classes = [classes[idx] for idx in dominating_classes_index]

# Print the dominating classes
print(dominating_classes)


['Question', 'Positive', 'Question', 'Question', 'Question', 'Recommendation', 'Positive', 'Negative', 'Recommendation']


In [ ]:
classifier.save('MODEL_FINAL_1', save_format='tf')


In [ ]:
# Assuming you have already mounted your Google Drive
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

# Save model weights to Google Drive temporary space
weights_path = '/content/drive/My Drive/weights.h5'
classifier.save_weights(weights_path)


Mounted at /content/drive


In [ ]:
import shutil

# Define paths
source_path = "/content/weights_path.data-00000-of-00001"
destination_path = "/content/drive/My Drive/weights_path.data-00000-of-00001"

# Copy the file to Google Drive
shutil.copy(source_path, destination_path)


'/content/drive/My Drive/weights_path.data-00000-of-00001'

In [ ]:
# Save the weights of your model
classifier.save_weights('bert_model_weights.h5')


In [ ]:
import tensorflow as tf
from transformers import BertTokenizer
from transformers import TFBertModel

# Define your model architecture
class BERTForClassification(tf.keras.Model):
    def __init__(self, bert_model, num_classes):
        super().__init__()
        self.bert = bert_model
        self.fc = tf.keras.layers.Dense(num_classes, activation='softmax')

    def call(self, inputs, attention_mask=None, token_type_ids=None):
        outputs = self.bert(inputs, attention_mask=attention_mask, token_type_ids=token_type_ids)
        pooled_output = outputs[1]  # Assuming BERT returns pooled output in position 1
        return self.fc(pooled_output)

# Load the BERT model
bert_model = TFBertModel.from_pretrained('bert-base-multilingual-cased')

# Define the number of classes
NUM_CLASSES = 5  # Replace with your number of classes

# Create an instance of your model
model = BERTForClassification(bert_model, NUM_CLASSES)

# Call the model to initialize its variables
dummy_input = tf.ones((1, 71), dtype=tf.int32)  # Example input shape, adjust as needed
_ = model(dummy_input)

# Load the weights for your model
model.load_weights('bert_model_weights.h5')

# Create an instance of the BERT tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-cased')

# List of testing lines
testing_lines = [
    "BERT aik acha model hai?? btao zra",
    "Very nice explanation thanks",
    "Am a commerce background can I learn it?",
    "Hi .kasi hai ap main ap ko bhot follow krti hon main computer science ki student ho but medical background ha mera 1st semester ha or main achy sa coding sekhna chahti hon c language sekh rahi hon lakin abhi tak mughy nahi ati c language kia karon kasa logic build karon",
    "Cloud computing as a fresher good or not ?",
    "Mam please c++ language video",
    "Aap bolti bahut aache se hain",
    "Didi eek video VOIP pae bana lon mera exam hai",
    "Need a roadmap for cloud computing and projects that can be done on them"
]

# Tokenize and preprocess the new data
inputs = tokenizer(testing_lines, padding=True, truncation=True, return_tensors='tf')
input_ids = inputs['input_ids']
attention_mask = inputs['attention_mask']
token_type_ids = inputs['token_type_ids']


print("Input IDs shape:", input_ids)
print("Attention mask shape:", attention_mask)
print("Token type IDs shape:", token_type_ids)

# Make predictions
predictions = model.predict({'input_ids': input_ids, 'attention_mask': attention_mask, 'token_type_ids': token_type_ids})

# Print predictions
print(predictions)


Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.weight', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

Input IDs shape: tf.Tensor(
[[   101  46291  46935  11346  10174  33478  10113  13192  13080    136
     136    170  50456    194  10288    102      0      0      0      0
       0      0      0      0      0      0      0      0      0      0
       0      0      0      0      0      0      0      0      0      0
       0      0      0      0      0      0      0      0      0      0
       0      0      0      0      0      0      0      0      0      0
       0      0      0      0      0      0      0      0      0      0
       0]
 [   101  37282  46267  10112  88840  69892    102      0      0      0
       0      0      0      0      0      0      0      0      0      0
       0      0      0      0      0      0      0      0      0      0
       0      0      0      0      0      0      0      0      0      0
       0      0      0      0      0      0      0      0      0      0
       0      0      0      0      0      0      0      0      0      0
       0      0      0    

In [ ]:
import numpy as np

# Convert predictions to numpy array
predictions_array = np.array(predictions)

# Get the index of the class with the highest probability for each prediction
dominating_classes_index = np.argmax(predictions_array, axis=1)

# Define the classes corresponding to the indices
classes = ['Positive', 'Negative', 'Neutral', 'Recommendation', 'Question']

# Get the dominating class for each prediction
dominating_classes = [classes[idx] for idx in dominating_classes_index]

# Print the dominating classes
print(dominating_classes)


In [ ]:
import tensorflow as tf
from transformers import BertTokenizer
from transformers import TFBertModel

# Define your model architecture
class BERTForClassification(tf.keras.Model):
    def __init__(self, bert_model, num_classes):
        super().__init__()
        self.bert = bert_model
        self.fc = tf.keras.layers.Dense(num_classes, activation='softmax')

    def call(self, inputs, attention_mask=None, token_type_ids=None):
        outputs = self.bert(inputs, attention_mask=attention_mask, token_type_ids=token_type_ids)
        pooled_output = outputs[1]  # Assuming BERT returns pooled output in position 1
        return self.fc(pooled_output)

# Load the BERT model
bert_model = TFBertModel.from_pretrained('bert-base-multilingual-cased')

# Define the number of classes
NUM_CLASSES = 5  # Replace with your number of classes

# Create an instance of your model
model = BERTForClassification(bert_model, NUM_CLASSES)

# Call the model to initialize its variables
dummy_input = tf.ones((1, 168), dtype=tf.int32)  # Example input shape, adjust as needed
_ = model(dummy_input)

# Load the weights for your model
model.load_weights('bert_model.h5')

# List of testing lines
testing_lines = [
    "BERT aik acha model hai?? btao zra",
    "Very nice explanation thanks",
    "Am a commerce background can I learn it?",
    "Hi .kasi hai ap main ap ko bhot follow krti hon main computer science ki student ho but medical background ha mera 1st semester ha or main achy sa coding sekhna chahti hon c language sekh rahi hon lakin abhi tak mughy nahi ati c language kia karon kasa logic build karon",
    "Cloud computing as a fresher good or not ?",
    "Mam please c++ language video",
    "Aap bolti bahut aache se hain",
    "Didi eek video VOIP pae bana lon mera exam hai",
    "Need a roadmap for cloud computing and projects that can be done on them"
]

# Tokenize and preprocess the new data
tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-cased')
inputs = tokenizer(testing_lines, padding=True, truncation=True, return_tensors='tf')

# Extract input tensors
input_ids = inputs['input_ids']
attention_mask = inputs['attention_mask']
token_type_ids = inputs['token_type_ids']

# Make predictions
predictions = model.predict({'input_ids': input_ids, 'attention_mask': attention_mask, 'token_type_ids': token_type_ids})

# Print predictions
print(predictions)


Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.weight']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w